import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CharactersService {

  constructor() { }
  ngOnInit(): void {
    //Called after the constructor, initializing input properties, and the first call to ngOnChanges.
    //Add 'implements OnInit' to the class.
  }
  characters:any = [
    {
      name:'DORA',
      image: 'https://www.noggin.com/app/uploads/2019/06/Dora-Copy.jpg',
      height:3.5,
      weight:35,
      iq:75,
      bravery:98,
      honesty:90,
      popularity:100,
    },
    {
      name:'BOOTS THE MONKEY',
      image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS-QItaQCiMZ_mI8ZKGbVwRWt05-uE0UelFw&s',
      height:2.1,
      weight:20,
      iq:68,
      bravery:65,
      honesty:70,
      popularity:100,
    },
    {
      name:'SWIPER THE FOX',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWVX9ab04egc9j9c7YbostqQuaqmED83UyCA&s',
      height:3.4,
      weight:35,
      iq:85,
      bravery:90,
      honesty:80,
      popularity:100,
    },
    {
      name:'BACKPACK',
      image:'assets/backpack.jpeg',
      height:1.25,
      weight:15,
      iq:61,
      bravery:55,
      honesty:52, 
      popularity:100,
    },
    {
      name:'Lion The Circus',
      image: 'assets/lion-the-circus.jpeg',
      height:3.3,
      weight:100,
      iq:90,
      bravery:90,
      honesty:85,
      popularity:100,
    },
    {
      name:'Little Lamb',
      image: 'assets/littlelamb.jpg',
      height:1.5,
      weight:10,
      iq:75,
      bravery:85,
      honesty:80,
      popularity:100,
    },
    {
      name:'Sataclcs',
      image: 'assets/santa.webp',
      height:3.10,
      weight:50,
      iq:90,
      bravery:95,
      honesty:85,
      popularity:100,
    },
    {
      name:'Diego',
      image: 'assets/diego.webp',
      height:3.5,
      weight:40,
      iq:75,
      bravery:65,
      honesty:35,
      popularity:100,
    },
    {
      name:'Tico The Squarell',
      image: 'assets/tico.jpeg',
      height:3.2,
      weight:45,
      iq:85,
      bravery:80,
      honesty:75,
      popularity:100,
    },
    {
      name:'Pirate Pig',
      image: 'assets/pig.webp',
      height:2.9,
      weight:90,
      iq:85,
      bravery:80,
      honesty:75,
      popularity:100,
    },
    {
      name:'Crumpy Old Troll',
      image: 'assets/old.jpeg',
      height:2.45,
      weight:35,
      iq:61,
      bravery:68,
      honesty:67,
      popularity:100,
    },
    {
      name:'Senor Tucan',
      image: 'assets/tucan.png',
      height:1.0,
      weight:4,
      iq:58,
      bravery:62,
      honesty:51,
      popularity:100,
    },
    {
      name:'Baby Crab',
      image: 'assets/crab.jpeg',
      height:1.0,
      weight:20,
      iq:85,
      bravery:80,
      honesty:65,
      popularity:100,
    },
    {
      name:'Maestra Teacher',
      image: 'assets/teacher.jpg',
      height:5.2,
      weight:60,
      iq:98,
      bravery:90,
      honesty:96,
      popularity:100,
    },
    {
      name:'Baby Dino',
      image: 'assets/dino.jpg',
      height:11,
      weight:120,
      iq:80,
      bravery:85,
      honesty:70,
      popularity:100,
    },
    {
      name:'Baby Jaguar',
      image: 'assets/jag.png',
      height:2.2,
      weight:25,
      iq:53,
      bravery:65,
      honesty:61,
      popularity:100,
    },
    {
      name:'Benny',
      image: 'assets/bunny.jpeg',
      height:3.0,
      weight:95,
      iq:90,
      bravery:85,
      honesty:80,
      popularity:100,
    },
    {
      name:'Papi',
      image: 'assets/papy.jpg',
      height:5.10,
      weight:85,
      iq:90,
      bravery:95,
      honesty:90,
      popularity:100,
    },
    {
      name:'Isa The Iguana',
      image: 'assets/isa.webp',
      height:3.0,
      weight:35,
      iq:90,
      bravery:80,
      honesty:25,
      popularity:100,
    },
    {
      name:'The big Red Chicken',
      image: 'assets/chicken.jpeg',
      height:9.1,
      weight:4,
      iq:85,
      bravery:75,
      honesty:65,
      popularity:100,
    },
    {
      name:'Map',
      image: 'assets/map.webp',
      height:2,
      weight:2,
      iq:85,
      bravery:90,
      honesty:95,
      popularity:100,
    },
  ]
}
